// Package sdk provides types and helpers for building OSG WASM plugins in
// Go (compiled with TinyGo).
//
// A plugin is a WASM module that exports three functions:
//
//	alloc(size i32) -> i32
//	dealloc(ptr i32, len i32)
//	handle_event(ptr i32, len i32) -> i64
//
// And optionally:
//
//	plugin_info() -> i64
//
// The host passes JSON-encoded Event structs through shared memory. The
// plugin processes them and returns an optional JSON-encoded Response.
//
// # Quick Start
//
// A minimal plugin using this SDK:
//
//	package main
//
//	import "osg/internal/plugin/sdk"
//
//	var plugin = sdk.NewPlugin(sdk.PluginMeta{
//	    Name:    "my-plugin",
//	    Version: "1.0.0",
//	    Hooks:   []string{"build.finished"},
//	})
//
//	func init() {
//	    plugin.On("build.finished", func(ev sdk.Event) *sdk.Response {
//	        // your logic here
//	        return nil
//	    })
//	}
//
//	func main() {}  // required by TinyGo, but unused
//
// The SDK automatically generates the WASM ABI exports via go:wasmexport
// directives. See the scaffold generated by `osg plugin init --lang=go`.
package sdk

import (
	"encoding/json"
	"unsafe"
)

// Event is the input received from the OSG host for each hook invocation.
type Event struct {
	Type    string         `json:"type"`
	Payload map[string]any `json:"payload"`
}

// Response is the optional output returned to the OSG host. The Payload
// fields are deep-merged into the template render context.
type Response struct {
	Payload map[string]any `json:"payload"`
}

// PluginMeta describes the plugin to the host. It is returned by the
// plugin_info export.
type PluginMeta struct {
	Name        string   `json:"name"`
	Version     string   `json:"version"`
	Description string   `json:"description,omitempty"`
	Author      string   `json:"author,omitempty"`
	Hooks       []string `json:"hooks"`
}

// HandlerFunc processes an event and returns an optional response.
// Return nil to indicate no overrides.
type HandlerFunc func(Event) *Response

// Plugin is the main SDK entry point. Register handlers with On() and
// the SDK wires up the WASM ABI automatically.
type Plugin struct {
	meta     PluginMeta
	handlers map[string]HandlerFunc
}

// globalPlugin is the singleton accessed by the WASM ABI exports.
// Set via NewPlugin().
var globalPlugin *Plugin

// NewPlugin creates a plugin instance and registers it as the global
// handler for WASM ABI exports. Only one plugin per module is supported.
func NewPlugin(meta PluginMeta) *Plugin {
	p := &Plugin{
		meta:     meta,
		handlers: make(map[string]HandlerFunc),
	}
	globalPlugin = p
	return p
}

// On registers a handler for the given hook name.
//
// Available hooks:
//   - "config.validate"
//   - "build.started"
//   - "content.transform"
//   - "page.render"
//   - "section.render"
//   - "taxonomy.list.render"
//   - "taxonomy.term.render"
//   - "image.process"
//   - "build.finished"
//   - "after.build"
func (p *Plugin) On(hook string, fn HandlerFunc) {
	p.handlers[hook] = fn
}

// HandleEvent is called by the WASM ABI bridge. It unmarshals the JSON
// event, dispatches to the registered handler, and returns the serialized
// response as a byte slice (or nil).
func HandleEvent(data []byte) []byte {
	if globalPlugin == nil {
		return nil
	}

	var ev Event
	if err := json.Unmarshal(data, &ev); err != nil {
		return nil
	}

	handler, ok := globalPlugin.handlers[ev.Type]
	if !ok {
		return nil
	}

	resp := handler(ev)
	if resp == nil {
		return nil
	}

	out, err := json.Marshal(resp)
	if err != nil {
		return nil
	}
	return out
}

// GetPluginInfo returns the plugin metadata as JSON bytes.
func GetPluginInfo() []byte {
	if globalPlugin == nil {
		return nil
	}
	data, err := json.Marshal(globalPlugin.meta)
	if err != nil {
		return nil
	}
	return data
}

// --- Helpers for accessing payload fields ---

// GetString extracts a string value from a nested map path.
// Example: GetString(ev.Payload, "config", "public_dir")
func GetString(m map[string]any, keys ...string) string {
	val := getNestedValue(m, keys...)
	if val == nil {
		return ""
	}
	if s, ok := val.(string); ok {
		return s
	}
	return ""
}

// GetBool extracts a boolean value from a nested map path.
func GetBool(m map[string]any, keys ...string) bool {
	val := getNestedValue(m, keys...)
	if val == nil {
		return false
	}
	if b, ok := val.(bool); ok {
		return b
	}
	return false
}

// GetFloat extracts a float64 value from a nested map path.
// JSON numbers are always float64 after unmarshaling.
func GetFloat(m map[string]any, keys ...string) float64 {
	val := getNestedValue(m, keys...)
	if val == nil {
		return 0
	}
	if f, ok := val.(float64); ok {
		return f
	}
	return 0
}

// GetSlice extracts a []any value from a nested map path.
func GetSlice(m map[string]any, keys ...string) []any {
	val := getNestedValue(m, keys...)
	if val == nil {
		return nil
	}
	if s, ok := val.([]any); ok {
		return s
	}
	return nil
}

// GetMap extracts a map[string]any value from a nested map path.
func GetMap(m map[string]any, keys ...string) map[string]any {
	val := getNestedValue(m, keys...)
	if val == nil {
		return nil
	}
	if m, ok := val.(map[string]any); ok {
		return m
	}
	return nil
}

func getNestedValue(m map[string]any, keys ...string) any {
	if len(keys) == 0 {
		return nil
	}
	current := any(m)
	for _, key := range keys {
		cm, ok := current.(map[string]any)
		if !ok {
			return nil
		}
		current = cm[key]
	}
	return current
}

// --- Low-level ABI helpers (used by the WASM export bridge) ---

// PackPtrLen packs a pointer and length into a single uint64 value
// using the OSG convention: high 32 bits = ptr, low 32 bits = len.
func PackPtrLen(ptr uint32, length uint32) uint64 {
	return (uint64(ptr) << 32) | uint64(length)
}

// BytesToWasm copies a Go byte slice into WASM linear memory via the
// alloc export pattern and returns the packed ptr/len. If data is nil
// or empty, returns 0.
func BytesToWasm(data []byte) uint64 {
	if len(data) == 0 {
		return 0
	}
	ptr := Alloc(int32(len(data)))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(uintptr(ptr))), len(data)), data)
	return PackPtrLen(uint32(ptr), uint32(len(data)))
}

// Alloc allocates n bytes of memory and returns a pointer to it.
// This is the underlying implementation used by the alloc WASM export.
func Alloc(n int32) int32 {
	buf := make([]byte, n)
	if len(buf) == 0 {
		return 0
	}
	return int32(uintptr(unsafe.Pointer(&buf[0])))
}

// SliceFromPtr creates a byte slice from a raw pointer and length.
// Used by the handle_event bridge to read input data.
func SliceFromPtr(ptr int32, length int32) []byte {
	if ptr == 0 || length == 0 {
		return nil
	}
	return unsafe.Slice((*byte)(unsafe.Pointer(uintptr(ptr))), length)
}
